# Generated by Django 4.2.1 on 2023-12-26 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('icono', models.CharField(max_length=255)),
                ('imagen', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('numHuespedes', models.IntegerField()),
                ('numCamas', models.IntegerField(blank=True, null=True)),
                ('numBanos', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('valorNoche', models.IntegerField()),
                ('lugar', models.CharField(max_length=50)),
                ('desLugar', models.TextField()),
                ('latitud', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
                ('continente', models.CharField(choices=[('AMÉRICA DEL SUR', 'AMÉRICA DEL SUR'), ('AMÉRICA DEL NORTE', 'AMÉRICA DEL NORTE'), ('CENTRO AMÉRICA', 'CENTRO AMÉRICA'), ('EUROPA', 'EUROPA'), ('ASIA', 'ASIA'), ('ÁFRICA', 'ÁFRICA'), ('OCEANÍA', 'OCEANÍA')], default='AMÉRICA DEL NORTE', max_length=50)),
                ('valorLimpieza', models.IntegerField()),
                ('comision', models.IntegerField()),
                ('politica', models.BooleanField(blank=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCompleto', models.CharField(max_length=150)),
                ('tipoDocumento', models.CharField(choices=[('CC', 'Cedula de Ciudadanía'), ('CE', 'Cedula de Extranjería'), ('PAS', 'Pasaporte'), ('NIT', 'Número de identificación tributaria')], default='CC', max_length=3)),
                ('numeroDocumento', models.CharField(max_length=20)),
                ('correoElectronico', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12)),
                ('telefonoCelular', models.CharField(max_length=12)),
                ('idioma', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('rolAdmin', models.BooleanField(blank=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('banco', models.CharField(choices=[('BANCOLOMBIA', 'BANCOLOMBIA'), ('Banco de Bogotá', 'Banco de Bogotá'), ('Banco caja social', 'Banco caja social'), ('Av Villas', 'Av Villas'), ('Banco de occidente', 'Banco de occidente'), ('Banco Popular', 'Banco Popular'), ('Banco Agrario', 'Banco Agrario'), ('Davivienda', 'Davivienda'), ('Colpatria', 'Colpatria')], default='BANCOLOMBIA', max_length=50)),
                ('numeroCuenta', models.CharField(blank=True, max_length=20, null=True)),
                ('daviplata', models.CharField(blank=True, max_length=12, null=True)),
                ('fechaRegistro', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SitioVisitado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaVista', models.DateField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Seguridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField()),
                ('fecha', models.DateField()),
                ('fechaEntrada', models.DateField()),
                ('fechaSalida', models.DateField()),
                ('numAdultos', models.IntegerField()),
                ('numNinos', models.IntegerField(blank=True, null=True)),
                ('numBebes', models.IntegerField(blank=True, null=True)),
                ('numMascotas', models.IntegerField(blank=True, null=True)),
                ('precioFinal', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('comision', models.IntegerField()),
                ('gananciaAnfitrion', models.IntegerField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='PagoAnfitrion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRadicado', models.DateField()),
                ('fechaPago', models.DateField(blank=True, null=True)),
                ('medioPago', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPago', models.DateField()),
                ('medioPago', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('valor', models.IntegerField()),
                ('valorDevolucion', models.IntegerField()),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=255)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField()),
                ('fecha', models.DateField()),
                ('calLimpieza', models.FloatField()),
                ('calComunicacion', models.FloatField()),
                ('calLlegada', models.FloatField()),
                ('calFiabilidad', models.FloatField()),
                ('calUbicacion', models.FloatField()),
                ('calPrecio', models.FloatField()),
                ('descripcion', models.TextField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sitio')),
            ],
        ),
    ]
