# Generated by Django 4.2.1 on 2024-01-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sitio_categoria_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='desComunicacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='desFiabilidad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='desLimpieza',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='desLlegada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='desPrecio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='desUbicacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
