# Generated by Django 4.2.1 on 2024-01-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comentario_descomunicacion_comentario_desfiabilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='numHuespedes',
            field=models.IntegerField(null=True),
        ),
    ]
