# Generated by Django 4.2.1 on 2024-01-08 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reserva_numhuespedes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRadicado', models.DateField()),
                ('fechaPago', models.DateField(blank=True, null=True)),
                ('valor', models.IntegerField()),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reserva')),
            ],
        ),
    ]
