# Generated by Django 4.2.1 on 2024-01-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_devolucion_fechapago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='latitud',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='longitud',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='lugar',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
